#!/bin/ruby


#["a", "a", "c", "e", "h", "k", "k", "n", "r", "r"]


def hackerrank(string)
    string = string.scan(/[acehknr]/)
    hack = "hackerrank".split("");
    i = 0;
    j = 0;
    while i < string.length
        j += 1 if string[i] == hack[j]
        return "YES" if j == hack.length
        i += 1
    end
    return "NO"
end

# q = gets.strip.to_i
# for a0 in (0..q-1)
#     s = gets.strip
#     puts hackerrank(s)
# end
input = "bvxqokorcxbivcnvdmcametgxvzftjkiyzatzatnapwttpxwqegvxllbtvxf
nmwwbkicnaxmjxwgecexnndlgmwfsiusksumczuzfpajpmsboatncwzecbkxavloimnkllz
iuvaikvogykbcqizbqmdxyipclavzgvgonstdzpzskwvixgdfyblmmymtxwoxsoyqlqzbsy
uatyebgkwznlnxqjefgkeluqcvtgmtvjsbaalxpqdmkptbqyefleiulcbsijglnawbwmbzuq
ybuqfmpewqnvnxqpawngtmuplfvlctyysbicubvnbjaayepapsotfzzfpdifsnpovufuuxs
evipbbylkyoboqjatntvtqpbxjgposuleiqjnzbdecuzdjujweuztnwoggaoljoniwpkdbt
tjpnfomegodafcqpfjoxcpaiejdnnkvavjxgnbffuzkaozveqekvmdvwfnldlpzbkyioczs
qnggspqgeyktlksupywxkgydwzovlndectcjwnxikuwcqdapqlvsdlboaesypkpujcdmwqmv
foqlsptkkzwsmauadiuqoygoucdzcgoodmdmwcaafwygzktolpqzvyovekgpobndncyzmpe
mzsxtzovjxzettonibczyyxdfvbealnzsoysminakkcwlmnnxnlultsnagfllmckenvbyim
cmxsxkwfxcozjniayaydmausxgwntoxplvmnbqmgnbqibbksgxzjydswmdlmxdcjzszicsow
tnntakaopldgywibqdbiapexeumwizozfdjzdjfevwkycctuoplypfvnlclilayfgntuaid
ctvxntujlaqzizoiueqgkydnzqfeaizobbniyswfaooxuzxfcuvsplksvgqnpitctdkyml
ytpxtzikveznmvzakpiecagzilefzluzfxexzwiwcfmwfgbvumcalixagmikxgdwjdblzl
owyximkgwtwgkcycluaiuddfocelymvfccfbwykfobxpuwxkbppsgyndquubdvtmzjfeoidd
eydndzpciidysilvtmtfjiejaodwakwbmqgcgklvljfykmglvikblmdyynxuigxgkujcjte
njgpdimocywaxfwqusyzpytwxpvsbxqqqjbcvzqfmppaixnofygmxilxijxzyxgmfjiosgxa
sfbnanzqawmiuzdpbygzussrymjsbdjwsxzxxpjzskoqqslqwxlnvqycqtmsklyywuqfdkfo
fwtoeccajywebpwwxydjvqcdgaaztmxntemvlqxpsstzlzullnpxbyjywstjelfjeizvzj
fguimgoacptxioauqiqkabptbsebcdzctdtyqapbjastgmlvoekosvkfbzfbnwkoiytspdk
eoywpaajkqvlgvjqqgdomywcsgojgkiewjcytaskqgloqtdjbssfjdcgxmjtsbmmgkbdakx
clflnmadmbnzljqqunuwwvvquxjtiiazivxoogvbmpajvbtclkjjyjovbstpvgspigyctgc
bxxockkvlzllftwzbnlpnjxoppkluqoxkpaauipgndpixfeqyucgtyqfngemdnyfywiyafx
tcfypgcvslwmzxtmxqljdcxibsfctqsgipwqjcvkcziwjeyzkjocynfmbwmokmkbitlxceu
cgksjytasldlngbvzegokdppywngxululnxvxcuiffgiyzjbfqfkfdnqwtmaknebokdistb
gvunmdfdplxfosoixqcaalexpnvffaxtzmdafsczxbtwejnabxiugiecdjvjaduyswnqmgog
jsnqajqjvekonsfamdiblvwidimdkblpbzcubdieztmmyibdzaoljbaiptpvqaofgnxcuwmy
cdqijtwonoivfxjdayagywnazkzgmlcdwcjvssyjndebotuybwkffvazpbcddkgoqjtqtpxl
josfcsebmoyajqagcfpngmjfcsjgnzcmlftngnococzvnybagwdfgmnvlcsuyxniomxqcmae
bfadlopzcznepbixvkxxvvsajitzxcvvbezmbnglkwsnmqxecgfjxcvzsysokyewupakmfjj
twjiqwexitgoznwtimxzgewskdmicmgmpoekeypqusfitatpfovzlgkgxizbntbjqpcafpzuz
wocpkyjguoqmcnpeivbdqldcqkawikuvkmdbqvaikitakpyfvgacxtiijcvjijaowtmixlc
oocdwgkeajvyfktgjwzzanxclapampbxgbmtetngyyumkemiqiggfxvoubsiemjwfyjzwls
xqfpotdbpusluexmuwkyzqsjlsloldiqyjblpsujxtfeeixluktalimfdiiwubqvdsmbbjxz
cvdqtgbtevmlkolmnsiydxuaaubulnzscoopuqakwnnwgnvpignakbpwkgapuwuawdmdactl
uoovbbotgbafszbgukovsdnknakzyczlzqvqmeenpiyywcioanbbqffscplmntvaspeqaqml
xjywonjenoozpqebjliftfmlbeymayspcyllcetbtmoidbmwdonfnuxpttqbaoeiweykwtua
kmajwlzuymbbcxcnnxezkzypyqaufbxziyfyggsfkjyjzlqqxnuypvimvwbbxwlavxjninvx
jyddejclcaodwfucdsmkccvaoynvsficxzdnmyvfbdotsmncicjnsiqafizvibgqeapntkn
iagampbckuuezbnydoplvgjejqtilxajfqkkpxcdpyqbeiisucqybscyscscpaaqyvgmcmc
ijtwmkiaozeluxvukxbmizpxndyjxsuiaizawtxwoqjpugizvufwjvxscoeiqzdcqmcisckk
skpzovfeukzdamjilzedgpbnddstwoblwevduslwgxqvttjesioswkfgojkmdzgytvuugewe
sjgquvcdkuokzieaizeenqdazmeobcofxgldvkxqiewulyaqzxejbkpayjcywmaeuoxfgtd
ymvenxmfiqbvdzissqampwpooovsoiflpoqydauotdkqjefzqtuogaftyjmpuuxkqgkaczwi
syctlbqzsjusmapxtsyucsjzswbfcnqgzeasffawejjmvkaofoigkxzawcbfwvfejndvtokc
ljtdbsuieiqjnbesgbsjvslinnankqdobkkszaeknuddvuvgggdcyezlogexcpeqxuowjiwz
vbliiymtbdlkltsimlxnaunaywzgjczuymtwtekdcnjwadoxcbfjdqmdnevjglqmamkdmabm
mpigwtkgexknzqjdbtgvbzddvxvqqemnutoolglfjpkiuusilpqstsgvomtbgzcngfcjcdvv
iafqstxulqxqtwiulbmnqbfbvwsbkrgcmoifvfbtwfwjgsvaokzbicqxgpjopgyasxtcpyfy
lvodvtvfgsefulctkvwwyvlyngblgbbsnimeduwtsljfivqstkucdsgtwfpmdpeysogolim
yquyaqegdgzmtecdjvkoudddglgloknwetevoylfmuyzlyzmbnmidwqfjzfvqfsnyujzvowb
eaaxwexxoxbbacbxwjmxycocsjeywkinejdzvqoqwuygaibgtqjgfcntykovlnpgkexaegtgt
kbdnqybbyxyuolewqzmiygtgjjydkdwzuobxnmsyfvknpxtpjliokwiubfdmdyzuwwcbovz
zzzvinosvytlkospmtoffymqqxpfvlgzuwvbpkxmtkoulfqtepxnymktekecsbcjjepfkfy
mtknlsimdskbqblggvdsjmbeddyfqgydjocitgyaxfetweuqgddjblftvntcvsyfiaocolgw
zcwnaxjmknejyfqbcmnpxobbometbyxndxxvxoiizxtdtwziwnaytyjdibyiknunywxabvoo
bxvdqvdwefywecgcqtcdjwelycezpvepjqosglnwpmmvzkbeifdzwgjytespluszuwvqdtfx
ldyaqudvfeuybfyjvxsxsedmppkmgcpbgjlsqzsmijmnzawagoiegjjvacxbczbyauuntdyq
absfgdoxptqxlpdgkunovezpaadvynncqdsdxxjnzqyfluujkjemxnxqpklbnzluaxwjubjm
fvnkfwsxefmvabfeuvnfzioulufpzanmkkdbnvuelxugxngbezvyqcibeiudkvieaklzddeu
gnypwfebgpzxoqbpwoxwtmdvjfzvwncdosekzffuifkjyakdjpuypsdkvkgasqffxzqkmpmu
ejxgwcoppuidbgecndopibdotpdxkslywmcfaetmsxdkwypybggasmlwqjmvnlbivxketutv
xpwvgbzfgpmsvcvvtwkloeljxalxzzfgbbcllopakazjvzgqadvllywpxamyodlvvqmpqgfb
mcalnmzkqznflwvfzzaxdoyeczavqwpxuxglulkeaqumbdyzoutwtkbneoxlqlkleeotwtyd
zdcqipgyfdecjpyfvgzzmekmtlisyaldogvpwcqjdsgwucptuaibvntpukmgvjjansjkmpyl
vexmqgysjnwqnwudoqoquflcqyzffewolymmosbxvcgbnaauxopkllslgeguzngxszbkbdvf
nvaitxtaimctciiydovnnffaamfvtawoqazqkdnpwuxkvxfapbogupbfoguzdivsxuyvdgyv
wkcvkoptkdiunguslfafuoixcvwgxauqjnpfimlkavqpdomyiefhoisfujicsxglubqntfam
sndkvgviukzfoxipwgtuewjpnzpllfmsilwgbvoajuydsnjollmljygoqfjujazlgxdwbwoi
ywlejidwjigiftnnbfnxzqvqyempksflipedanfpxknvmzezpfytiwwoadjfibznntgwtwwk
kvqvdoqpysbfmbzkcxiwqftcgpwobcsefynfsxmsjmnlspimoftwcxkmzvudzgydagjajfdv
nlgsybafzmccsykpjpvuekxkgkcfdniecdoquugwegimkdioekyubebqlwwuszbiynpwffey
buuiomwwsdppdneuunjgxktscgzzyqgwlesywoibkfidnogmgbtasxleelkxtecwssjusbcp
tnggtvxpincqvujktpzhm"

input2 = "bvxqokorcxbivcnvdmcametgxvzftjkiyzatzatnapwttpxwqegvxllbtvxfnm
wwbkicnaxmjxwgecexnndlgmwfsiusksumczuzfpajpmsboatncwzecbkxavloimnkllziuv
aikvogykbcqizbqmdxyipclavzgvgonstdzpzskwvixgdfyblmmymtxwoxsoyqlqzbsy"

puts hackerrank(input)
puts hackerrank(input2)
